version: '3.3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_URL=${DATABASE_URL}
    restart: always

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  mongo_db:
    image: mongo:4.4

  neo4j_db:
    image: neo4j:4.3
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}