version: '3.3'

services:
  app:
    build: .
    ports:
      - "${PORT:-3001}:${PORT:-3000}"
    depends_on:
      - mysql_db
      - mongo_db
      - neo4j_db
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Waiting for MySQL...' &&
        sleep 10 &&
        echo 'Running Prisma migrations...' &&
        npx prisma migrate deploy &&
        echo 'Starting app...' &&
        npm start
      "

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smartrecipe
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  mongo_db:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db

  neo4j_db:
    image: neo4j:4.3
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data

volumes:
  mysql_data:
  mongo_data:
  neo4j_data: