version: '3.3'

services:
  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - mysql_db
      - mongo_db
      - neo4j_db
    environment:
      - NEO4J_URI=bolt://neo4j_db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - MONGODB_URI=mongodb://mongo_db:27017/smartrecipe
      - DATABASE_URL=mysql://root:password@mysql_db:3306/smartrecipe

    command: sh -c "sleep 10 && npx prisma migrate deploy && npm start"

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smartrecipe
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  mongo_db:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db

  neo4j_db:
    image: neo4j:4.3
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data

volumes:
  mysql_data:
  mongo_data:
  neo4j_data: