[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "3000"

[test]
command = "npm test"
onFailure = "FAIL_DEPLOYMENT"